export controller0=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=controller0" | jq -r '.Reservations[].Instances[].PrivateDnsName' |sed "s/\..*//")
export controller1=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=controller1" | jq -r '.Reservations[].Instances[].PrivateDnsName' |sed "s/\..*//")
export controller2=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=controller2" | jq -r '.Reservations[].Instances[].PrivateDnsName' |sed "s/\..*//")
export worker0=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=worker0" | jq -r '.Reservations[].Instances[].PrivateDnsName' |sed "s/\..*//")
export worker1=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=worker1" | jq -r '.Reservations[].Instances[].PrivateDnsName' |sed "s/\..*//")
export worker2=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=worker2" | jq -r '.Reservations[].Instances[].PrivateDnsName' |sed "s/\..*//")
export controller0pub=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=controller0" | jq -r '.Reservations[].Instances[].NetworkInterfaces[].Association.PublicIp')
export controller1pub=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=controller1" | jq -r '.Reservations[].Instances[].NetworkInterfaces[].Association.PublicIp')
export controller2pub=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=controller2" | jq -r '.Reservations[].Instances[].NetworkInterfaces[].Association.PublicIp')
export worker0pub=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=worker0" | jq -r '.Reservations[].Instances[].NetworkInterfaces[].Association.PublicIp')
export worker1pub=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=worker1" | jq -r '.Reservations[].Instances[].NetworkInterfaces[].Association.PublicIp')
export worker2pub=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=worker2" | jq -r '.Reservations[].Instances[].NetworkInterfaces[].Association.PublicIp')
export controller0prv=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=controller0" | jq -r '.Reservations[].Instances[].NetworkInterfaces[].PrivateIpAddress')
export controller1prv=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=controller1" | jq -r '.Reservations[].Instances[].NetworkInterfaces[].PrivateIpAddress')
export controller2prv=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=controller2" | jq -r '.Reservations[].Instances[].NetworkInterfaces[].PrivateIpAddress')
export worker0prv=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=worker0" | jq -r '.Reservations[].Instances[].NetworkInterfaces[].PrivateIpAddress')
export worker1prv=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=worker1" | jq -r '.Reservations[].Instances[].NetworkInterfaces[].PrivateIpAddress')
export worker2prv=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=worker2" | jq -r '.Reservations[].Instances[].NetworkInterfaces[].PrivateIpAddress')